# Generated by Django 5.1.4 on 2024-12-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchQuerry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.URLField()),
                ("description", models.TextField()),
                ("audio_source", models.URLField()),
                ("singer", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=100)),
                ("released_on", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
