# Generated by Django 5.1.4 on 2025-01-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="singers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.URLField()),
                ("description", models.TextField()),
                ("created", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
