# Generated by Django 5.1.4 on 2025-01-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0002_singers"),
    ]

    operations = [
        migrations.AddField(
            model_name="singers",
            name="number_of_songs",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
