# Generated by Django 5.1.4 on 2025-01-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0003_singers_number_of_songs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Singer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="singers",
        ),
    ]
