# Generated by Django 5.1.4 on 2025-01-15 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0004_singer_delete_singers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song",
            old_name="singer",
            new_name="singers",
        ),
    ]
