# Generated by Django 5.1.4 on 2025-01-15 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0005_rename_singer_song_singers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song",
            old_name="singers",
            new_name="singer",
        ),
    ]
