# Generated by Django 5.1.4 on 2025-01-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0006_rename_singers_song_singer"),
    ]

    operations = [
        migrations.AddField(
            model_name="singer",
            name="song_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
