# Generated by Django 5.1.4 on 2025-01-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0007_singer_song_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="singer",
            name="image",
            field=models.ImageField(
                default="singer_images/default.png", upload_to="singer_images/"
            ),
        ),
    ]
