# Generated by Django 5.1.4 on 2025-01-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0009_alter_searchquerry_search"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchquerry",
            name="search",
            field=models.CharField(max_length=100),
        ),
    ]
